config/routes.rb
AnneCarson::Application.routes.draw do
 root to: "homes#index"
 resource :session, only: [:new, :create, :destroy]
 resources :users, only: [:new, :create]
 resources :decks do 
 	resources :cards, except: :index
  
end
end



#   Prefix Verb   URI Pattern                              Controller#Action
#     deck_cards GET    /decks/:deck_id/cards(.:format)          cards#index
#                POST   /decks/:deck_id/cards(.:format)          cards#create
#  new_deck_card GET    /decks/:deck_id/cards/new(.:format)      cards#new
# edit_deck_card GET    /decks/:deck_id/cards/:id/edit(.:format) cards#edit
#      deck_card GET    /decks/:deck_id/cards/:id(.:format)      cards#show
#                PATCH  /decks/:deck_id/cards/:id(.:format)      cards#update
#                PUT    /decks/:deck_id/cards/:id(.:format)      cards#update
#                DELETE /decks/:deck_id/cards/:id(.:format)      cards#destroy
#          decks GET    /decks(.:format)                         decks#index
#                POST   /decks(.:format)                         decks#create
#       new_deck GET    /decks/new(.:format)                     decks#new
#      edit_deck GET    /decks/:id/edit(.:format)                decks#edit
#           deck GET    /decks/:id(.:format)                     decks#show
#                PATCH  /decks/:id(.:format)                     decks#update
#                PUT    /decks/:id(.:format)                     decks#update
               # DELETE /decks/:id(.:format)                     decks#destroy
 # asdsadsad

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
	belongs_to :user
	has_many :cards

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many:decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	helper_method :signed_in?

	protect_from_forgery with: :exception
	def current_user
		if cookies[:user_id]
			user_id = cookies.signed[:user_id]
			User.find_by_id(user_id)
		end 
	end
	def sign_in user
	cookies.signed[:user_id] = user.id 
end	
	private
	def deck_params
		params.require(:deck).permit(:name)
  	end
  	def card_params
    params.require(:card).permit(:front, :back)
  end

def signed_in?
	current_user 
	end
	def authenticate
	if !signed_in?
	redirect_to new_session_path
	end
end
end

 

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def show 
	 	@deck = find_deck
	 	# @cards = Card.find(params[:id])
	 	@cards = @deck.cards.find(params[:id])
	 	# @cards = @deck.first
	end

	def new 
		@deck = find_deck
		@card = @deck.cards.new
	end
	def create
		@deck = find_deck
		@card = @deck.cards.new(card_params)
		@card.save
		redirect_to @deck
	end

	def destroy
		@deck = find_deck
		@card = find_card(@deck)
		@card.destroy
		redirect_to deck_path(@deck.id)		
	end

	def edit
		@deck = find_deck
		@card = @deck.cards.find(params[:id])
	end

	def  update
		@deck = find_deck
		@card = @deck.cards.find(params[:id])
		@card.update(card_params)
		redirect_to deck
		# deck_path(@deck.id)
	end

	private 

	def find_deck
		Deck.find(params[:deck_id])
	end
	def find_card deck 
		deck.cards.find(params[:id])
	end

	# def create
	# 	@deck = Deck.new(deck_params)
	# 	@deck.save
	# 	redirect_to decks_path
	# end 

	# def edit 
	# 	@deck = Deck.find(params[:id])
	# end
	# def update
	# 	@deck = Deck.find(params[:id])
	# 	@deck.update_attributes(deck_params)
	# 	redirect_to @deck
 
	# end
	# def destroy
	# 	@deck = Deck.find(params[:id])
	# 	@deck.destroy
	# 	redirect_to decks_path
	# end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
 before_filter :authenticate


 def index 
 	@decks = current_user.decks 
 	
 	end

	def show 
	 	@deck = Deck.find(params[:id])
	 	@cards = @deck.cards 
	end

	def new 
		@deck = Deck.new 
	end

	def create
		@deck = Deck.new(deck_params)
		@deck.save
		redirect_to decks_path
	end 

	def edit 
		@deck = Deck.find(params[:id])
	end
	def update
		@deck = Deck.find(params[:id])
		@deck.update_attributes(deck_params)
		redirect_to @deck
 
	end
	def destroy
		@deck = Deck.find(params[:id])
		@deck.destroy
		redirect_to decks_path
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by_email(params[:session][:email])
		
		sign_in(user)
		redirect_to decks_path 
	end

	def destroy 
		cookies.delete(:user_id)
		redirect_to root_path 
	

	end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new 
	end

	def create
		@user = User.new(params[:user])
		@user.save
		sign_in @user
		redirect_to decks_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
		<div>
		<%= form.label :front %>
		<%= form.text_field :front%>
		</div>
		<div>
			<%= form.label :back %>
			<%= form.text_field :back %>
			</div>

app/views/cards/edit.html.erb
<%= form_for([@deck, @card]) do |form| %>
	<%= render form %>
			<%= form.submit "Update card" %>
	<% end %>

app/views/cards/new.html.erb
<%= form_for([@deck, @card]) do |form| %>
	<%= render form %>
			<%= form.submit "Create card" %>
	<% end %>

app/views/cards/show.html.erb
<b><%= link_to @deck.name, @deck %></b>



<div> THIS IS THE BACK <%= @cards.back %></div>

app/views/decks/edit.html.erb
<%= form_for(@deck) do |form| %>
	<div>
	<%= form.label :name %>
	<%= form.text_field :name%>
	</div>
	<%= form.submit "Edit deck" %>
	 
<% end %>

app/views/decks/index.html.erb
<%= link_to "New deck", new_deck_path %>

<% @decks.each do |deck| %>
<div><%= link_to decks.name, deck %></div>

<%= link_to "Edit", edit_deck_path(deck) %>
<%= link_to "Delete", deck , method: :delete, confirm: "Are You Sure?" %>
<% end %>

app/views/decks/new.html.erb
 <%= form_for(@deck) do |form| %>
	<div>
	<%= form.label :name %>
	<%= form.text_field :name%>
	</div>
	<%= form.submit "Create deck" %>
	 
<% end %>

app/views/decks/show.html.erb
<%= link_to "Decks", decks_path %>
<h2><%= @deck.name %></h2>
<%= link_to "New card", new_deck_card_path(@deck) %>
<% @cards.each do |card| %>
	<div><%= link_to card.front, [@deck, card] %>

	<p>Card Name: <%=  card.inspect %></p>
	
	<%= link_to "Edit", edit_deck_card_path(@deck, card) %>
	
	<%= link_to "Delete", [@deck, card], method: :delete, confirm: "Are you sure?" %></div>
	
	<% end %>

app/views/homes/index.html.erb
<HTML>
  <head>
  <title>POTENTIAL POETICS</title>
  <meta content="Words" name="description" />
  <meta content="poetics, oulipo, noly" name="keywords" />
</head>

    <SCRIPT language="JavaScript">
    
/* Helper functions */
          
    function splitOver ( instring, inArray, delimiters ) {
    	
    	/* Takes a string, an array, and a string */
    	/* Outputs an array of strings cut along  */
    	/* various delimiters                     */
	
		var lastCut = 0;
		var wordCount = 0;
		instring += delimiters[0];
	
		for (var i = 0; i < instring.length; i++) {
			for (var ii = 0; ii < delimiters.length; ii++) {
				if (instring[i] === delimiters[ii]) {
					if (instring.slice(lastCut, i) != "")  {
						inArray[wordCount] = instring.slice(lastCut, i);
						wordCount++;
						lastCut = i+1;
					}
				}
			}		
		}
	}  
	
	function rndRange ( min, max ) {
		/* Takes two integers, outputs an integer */
		return Math.floor((Math.random()*((max+1)-min)) + min); 
	}

/* Begin wordGram class */

	function wordGram () {
		this.txt = "";
		this.link = [];
		this.linkStrength = [];
		this.nLinks = 0;
	}

	wordGram.prototype.copy = function() {
    	var copy = new wordGram ()
    	copy.txt = this.txt
    	for (var i = 0; i < this.nLinks; i++) {
    		copy.link[i] = new wordGram();
        	copy.link[i] = this.link[i];
        	copy.linkStrenth[i] = new Number( this.linkStrength[i] )
    	}
	copy.nLinks = this.nLinks;
    	return copy;
	}

/* Begin wordGramContext class */

	var MAX_GRAMS = 200000;
	
	function wordGramContext () {
		this.nWordGrams = 0;
		this.words = [];
	}
	
	wordGramContext.prototype.wordGramByTxt = function ( intxt ) {
		/* Takes a string, returns the index in the array words[] */
		/* If the string is not found it returns -1               */
		for (var i = 0; i < this.nWordGrams; i++) {
			if (intxt === this.words[i].txt) { return i; }
		}
		return -1;
	}
	
	wordGramContext.prototype.addWord = function ( _word ) {
		/* Takes a string */
		if (_word === "") { return; }
		if (this.nWordGrams >= MAX_GRAMS) { console.log ("Memory Full"); return; }
		if (this.nWordGrams === 0) {
			this.nWordGrams++;
			this.words[0] = new wordGram();
			this.words[0].txt = _word;
			return;
			
		}
		for (var i=0; i < this.nWordGrams; i++) {
			if (this.words[i].txt === _word) { return; }
		}
		this.nWordGrams++;
		this.words[this.nWordGrams-1] = new wordGram();
		this.words[this.nWordGrams-1].txt = _word;
	}
	
	wordGramContext.prototype.addLink = function ( _word, _wordGram ) {
		/* Takes two strings */
		if (_word === "" || _wordGram === "" ) { return; }
		
		var idx1 = this.wordGramByTxt( _word ); 
		var idx2 = this.wordGramByTxt( _wordGram );
		
		if (idx1 === -1) { 
			this.addWord( _word );
			idx1 = this.nWordGrams-1;
		}
		
		if (idx2 === -1) { 
			this.addWord( _wordGram );
			idx2 = this.nWordGrams-1;
		}
		/* Does link exist? Then increment strength */
		
		if (this.words[idx1].nLinks != 0) { 
			for (var i =0; i < this.words[idx1].nLinks; i++) {
				if ( _wordGram === this.words[idx1].link[i] ) {
					this.words[idx1].linkStrength[i]++;
					return;
				}
			}
		}
		
		/* No link? Then add it */
		
		this.words[idx1].nLinks++;
		
		this.words[idx1].link[this.words[idx1].nLinks-1] = new wordGram();
		this.words[idx1].link[this.words[idx1].nLinks-1] = this.words[idx2];
		this.words[idx1].linkStrength[ this.words[idx1].nLinks-1 ] = new Number(1);
		
	}
	
	wordGramContext.prototype.eat = function ( instring ) {
		/* Takes a string */
		var inWords = new Array();
		var delim = " !?.,;:<>[]()\r\n";
		instring = instring.toLowerCase();
		splitOver ( instring, inWords, delim );
		
		for (var i=1; i < inWords.length; i++) {
			this.addLink ( inWords[i-1], inWords[i] );
		}
	}
	
	wordGramContext.prototype.genLine = function ( nWords ) {
		/* Takes an integer, returns a string */
		if (nWords === 0) { nWords = rndRange(3,10); }
		var res = "";
		if (this.nWordGrams === 0) { return "Eat some words."; }
		
		var pick = rndRange (0, this.nWordGrams-1);
						
		for (var i = 0; i < nWords; i++ ) {
			
			if (this.words[pick].nLinks > 1) {
				/* If there is more than 1 link */
				var pick1 = rndRange(0, this.words[pick].nLinks-1);
				var pick2 = rndRange(0, this.words[pick].nLinks-1);
				
				var roll1 = this.words[pick].linkStrength[pick1]*Math.random();
				var roll2 = this.words[pick].linkStrength[pick2]*Math.random();
				
				if (roll1 > roll2 ) {
					res = res + " " + this.words[pick].link[pick1].txt;
					pick = this.wordGramByTxt (this.words[pick].link[pick1].txt);
				} else {
					res = res + " " + this.words[pick].link[pick2].txt;
					pick = this.wordGramByTxt (this.words[pick].link[pick2].txt);					
				}
			} else {
				/* If there is only one link */
				if (this.words[pick].nLinks != 0) {
					res = res + " " + this.words[pick].link[0].txt;
					pick = this.wordGramByTxt (this.words[pick].link[0].txt);
				} else {
					pick = rndRange (0, this.nWordGrams-1);
				}
			}		
			
			if (pick === -1) { pick = rndRange (0, this.nWordGrams-1); }
		}
		return res;
	}
	
	var myContext = new wordGramContext();
	
    </SCRIPT>
   </HEAD>
   <BODY>
	<textarea id = "inputBox" text-align: center cols="10" rows="10" style="background-color:#000000;color:#FFFFFF;border:10px double #FFFFFF;">
keeping things whole

In a field
I am the absence
of field.
This is
always the case.
Wherever I am
I am what is missing.

When I walk
I part the air
and always
the air moves in 
to fill the spaces
where my body's been.

We all have reasons
for moving.
I move
to keep things whole.

	</textarea>
	<textarea id = "outputBox" text-align: center cols="10" rows="10" style="background-color:#000000;color:#FFFFFF;border:10px double #FFFFFF;"></textarea>
	<br>
	<button class="nolands-button" onclick="eatBox();">Eat these words</button>
	<button class="nolands-button" onclick="genLine();">Spit them out</button>
	<p id="text_">
	        <br>
	</p>

      <SCRIPT language="JavaScript">

	function eatBox() { 
	   var foo = document.getElementById( 'inputBox' ).value;
	   document.getElementById( 'inputBox' ).value = "";
	   myContext.eat (foo);  
 	 }
 	 
 	 function genLine( ) {
 	 	var nWords = window.prompt("How many words?","10");
 	 	var foo = myContext.genLine( parseInt(nWords) );
 	 	document.getElementById ('outputBox').value += foo + "\r\n"; 
 	 }

      </SCRIPT>
   </BODY>
</HTML>

app/views/layouts/_nav.html.erb
<div class="contain-to-grid">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">Name of Project</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>


      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="active"><a href="#">This is where we are</a></li>
          <li class="has-dropdown">
            <a href="#">Right Button Dropdown</a>
            <ul class="dropdown">
              <li><a href="#">First link in dropdown</a></li>
              <li class="active"><a href="#">Active link in dropdown</a></li>
            </ul>
          </li>
        </ul>
      </section>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>POETIC POTENTIAL</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(:session, url: users_path) do |form| %>
<div>
	<%= form.label :email %>
	<%= form.text_field :email %></div>
	<%= form.submit "Sign Up" %>

<% end %> 